CREATE TABLE STOCK(
  STOCK_ID NUMBER,
  STOCK_AVAILABLE NUMBER,
  STOCK_CAPACITY NUMBER,
  PRIMARY KEY(STOCK_ID)
);

CREATE TABLE PEN(
  PEN_ID NUMBER,
  PEN_DESCRIPTION VARCHAR2(255),
  PRIMARY KEY(PEN_ID)
);

CREATE TABLE CUSTOMER (
  CUST_ID NUMBER,
  CUST_SCORE NUMBER,
  PRIMARY KEY(CUST_ID)
);

----
CREATE DATABASE LINK DB_M1 CONNECT TO C##M1 IDENTIFIED BY A123
USING 'dung';

CREATE DATABASE LINK DB_M2 CONNECT TO C##M2 IDENTIFIED BY A123
USING 'hoa';

CREATE OR REPLACE PROCEDURE CREATE_BRAND_STORE(
  BRAND_STORE_ID NUMBER,
  BRAND_STORE_NAME VARCHAR2,
  BRAND_STORE_DISTRICT VARCHAR2,
  BRAND_STORE_CITY VARCHAR2,
  BRAND_STORE_HOTLINE VARCHAR2,
  BRAND_STORE_STATUS CHAR
) AS
BEGIN
  IF(BRAND_STORE_DISTRICT = 'Ho Chi Minh') THEN
    INSERT INTO C ##M1.BRAND_STORE@DB_M1 VALUES (
      NULL,
      BRAND_STORE_NAME,
      BRAND_STORE_DISTRICT,
      BRAND_STORE_CITY,
      BRAND_STORE_HOTLINE,
      NULL
    );
  ELSE
    IF(BRAND_STORE_DISTRICT = 'Ha Noi') THEN
      INSERT INTO C ##M2.BRAND_STORE@DB_M2 VALUES (
        NULL,
        BRAND_STORE_NAME,
        BRAND_STORE_DISTRICT,
        BRAND_STORE_CITY,
        BRAND_STORE_HOTLINE,
        NULL
      );
    ELSE
      IF(BRAND_STORE_DISTRICT = 'Da Nang') THEN
        INSERT INTO C ##M3.BRAND_STORE@DB_M3 VALUES (
          NULL,
          BRAND_STORE_NAME,
          BRAND_STORE_DISTRICT,
          BRAND_STORE_CITY,
          BRAND_STORE_HOTLINE,
          NULL
        );
      ELSE
        DBMS_OUTPUT.PUT_LINE('Do not have store at '
                             || BRAND_STORE_CITY);
      END IF;
    END IF;
  END IF;
END;

CREATE OR REPLACE PROCEDURE UPDATE_IMPORT_PEN( IMPORT_PEN_ID NUMBER, PEN_ID NUMBER, QUATITY NUMBER ) AS
BEGIN
  IF( IMPORT_PEN_ID > 0
  AND IMPORT_PEN_ID < 10000 ) THEN
    UPDATE M1.IMPORT_DETAIL_PEN @DB_M1
    SET
      QUATITY = QUATITY;
  ELSIF(IMPORT_PEN_ID < 10001) THEN
    UPDATE M2.IMPORT_DETAIL_PEN @DB_M2
    SET
      QUATITY = QUATITY;
  ELSIF(IMPORT_PEN_ID < 20001) THEN
    UPDATE M3.IMPORT_DETAIL_PEN @DB_M3
    SET
      QUATITY = QUATITY;
  ELSE
    DBMS_OUTPUT.PUT_LINE('import pen id in range [1..30000]');
  END IF;
END;

CREATE OR REPLACE PROCEDURE UPDATE_ORDERS_DETAILS( ORDER_ID NUMBER, STOCK_ID NUMBER, PEN_ID NUMBER, QUATITY NUMBER, ) AS
BEGIN
  IF( ORDER_ID > 0
  AND ORDER_ID < 100000 ) THEN
    UPDATE M1.ORDERS_DETAILS @DB_M1
    SET
      QUATITY = QUATITY
    WHERE
      ORDER_ID = ORDER_ID
      AND PEN_ID = PEN_ID;
    ELSEIF(ORDER_ID < 100001) THEN
      UPDATE M2.ORDERS_DETAILS @DB_M2
      SET
        QUATITY = QUATITY
      WHERE
        ORDER_ID = ORDER_ID
        AND PEN_ID = PEN_ID;
      ELSEIF(ORDER_ID < 200001) THEN
        UPDATE M3.ORDERS_DETAILS @DB_M3
        SET
          QUATITY = QUATITY
        WHERE
          ORDER_ID = ORDER_ID
          AND PEN_ID = PEN_ID;
      ELSE
        DBMS_OUTPUT.PUT_LINE('import pen id in range [1..300000]');
      END IF;
    END;
    UPDATE C ##M1.PEN@DB_M1
    SET
      PEN_PRICE = 1000
    WHERE
      PEN_ID = 1;
    SELECT
      *
    FROM
      C ##M1.PEN@DB_M1