CREATE TABLE CITY(
    CITY_ID NUMBER,
    CITY_NAME VARCHAR2(255),
    PRIMARY KEY(CITY_ID)
);

CREATE TABLE BRAND_STORE(
    BRAND_STORE_ID NUMBER,
    BRAND_STORE_NAME VARCHAR2(255),
    BRAND_STORE_DISTRICT VARCHAR2(255),
    BRAND_STORE_CITY_ID NUMBER,
    BRAND_STORE_HOTLINE VARCHAR2(15),
    PRIMARY KEY(BRAND_STORE_ID),
    FOREIGN KEY (BRAND_STORE_CITY_ID) REFERENCES CITY(CITY_ID)
);

CREATE TABLE STOCK(
    STOCK_ID NUMBER,
    STOCK_CITY_ID NUMBER,
    STOCK_NAME VARCHAR2(255),
    PRIMARY KEY(STOCK_ID),
    FOREIGN KEY (STOCK_CITY_ID) REFERENCES CITY(CITY_ID)
);

CREATE TABLE PEN(
    PEN_ID NUMBER,
    PEN_TITLE VARCHAR2(255),
    PEN_PRICE NUMBER,
    PRIMARY KEY(PEN_ID)
);

CREATE TABLE STOCK_DETAIL(
    PEN_ID NUMBER,
    STOCK_ID NUMBER,
    STOCK_AVAILABLE NUMBER,
    PRIMARY KEY(PEN_ID, STOCK_ID),
    FOREIGN KEY (STOCK_ID) REFERENCES STOCK(STOCK_ID),
    FOREIGN KEY (PEN_ID) REFERENCES PEN(PEN_ID)
);

CREATE TABLE IMPORT_PEN(
    IMPORT_PEN_ID NUMBER,
    STOCK_ID NUMBER,
    BRAND_STORE_ID NUMBER,
    CREATEDAT DATE DEFAULT SYSDATE NOT NULL,
    PRIMARY KEY(IMPORT_PEN_ID),
    FOREIGN KEY (STOCK_ID) REFERENCES STOCK(STOCK_ID),
    FOREIGN KEY (BRAND_STORE_ID) REFERENCES BRAND_STORE(BRAND_STORE_ID)
);

CREATE TABLE IMPORT_PEN_DETAIL(
    IMPORT_PEN_ID NUMBER,
    PEN_ID NUMBER,
    QUATITY NUMBER,
    PRIMARY KEY(IMPORT_PEN_ID, PEN_ID),
    FOREIGN KEY (IMPORT_PEN_ID) REFERENCES IMPORT_PEN(IMPORT_PEN_ID),
    FOREIGN KEY (PEN_ID) REFERENCES PEN(PEN_ID)
);

CREATE TABLE CUSTOMER (
    CUST_ID NUMBER,
    CUST_CITY_ID NUMBER,
    CUST_NAME VARCHAR2(255),
    CUST_NUMBER_PHONE VARCHAR2(15),
    PRIMARY KEY(CUST_ID),
    FOREIGN KEY (CUST_CITY_ID) REFERENCES CITY(CITY_ID)
);

CREATE TABLE ORDERS(
    ORDER_ID NUMBER,
    BRAND_STORE_ID NUMBER,
    STOCK_ID NUMBER,
    CUST_ID NUMBER,
    TOTAL NUMBER,
    ORDER_DATE DATE DEFAULT SYSDATE NOT NULL,
    PRIMARY KEY(ORDER_ID),
    FOREIGN KEY (BRAND_STORE_ID) REFERENCES BRAND_STORE(BRAND_STORE_ID),
    FOREIGN KEY (STOCK_ID) REFERENCES STOCK(STOCK_ID),
    FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(CUST_ID)
);

CREATE TABLE ORDERS_DETAILS(
    ORDER_ID NUMBER,
    PEN_ID NUMBER,
    QUATITY NUMBER,
    PRICE NUMBER,
    PRIMARY KEY(ORDER_ID, PEN_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (PEN_ID) REFERENCES PEN(PEN_ID)
);

INSERT INTO CITY VALUES (
    1,
    'Ha Noi'
);

INSERT INTO CITY VALUES (
    2,
    'Ho Chi Minh'
);

INSERT INTO CITY VALUES (
    3,
    'Da Nang'
);

INSERT INTO BRAND_STORE VALUES(
    1,
    'branch Ha Noi',
    'cau giay',
    1,
    '0123xxxx'
);

INSERT INTO BRAND_STORE VALUES(
    2,
    'branch Ho Chi Minh',
    'Thu Duc',
    2,
    '0123xxxx'
);

INSERT INTO BRAND_STORE VALUES(
    3,
    'branch Da Nang',
    'Thu Duc',
    3,
    '0123xxxx'
);