connect system/meo123;

DROP USER C##M1 CASCADE;

DROP ROLE C##ROLE_USER_GUEST1;

DROP USER C##GUEST1 CASCADE;

CREATE USER C##M1 IDENTIFIED BY a123;

GRANT CONNECT, RESOURCE, CREATE DATABASE LINK, CREATE ROLE, UNLIMITED TABLESPACE TO C##M1;

connect c##m1/a123;

--- enter script in file MX.sql

connect system/meo123;

CREATE ROLE C##ROLE_USER_GUEST1 NOT IDENTIFIED;

GRANT SELECT, INSERT, UPDATE, DELETE ON C##M1.STOCK TO C##ROLE_USER_GUEST1;

GRANT SELECT, INSERT, UPDATE, DELETE ON C##M1.PEN TO C##ROLE_USER_GUEST1;

GRANT SELECT, INSERT, UPDATE, DELETE ON C##M1.STOCK_DETAIL TO C##ROLE_USER_GUEST1;

GRANT SELECT, INSERT, UPDATE, DELETE ON C##M1.IMPORT_PEN TO C##ROLE_USER_GUEST1;

GRANT SELECT, INSERT, UPDATE, DELETE ON C##M1.IMPORT_PEN_DETAIL TO C##ROLE_USER_GUEST1;

GRANT SELECT, INSERT, UPDATE, DELETE ON C##M1.CUSTOMER TO C##ROLE_USER_GUEST1;

GRANT SELECT, INSERT, UPDATE, DELETE ON C##M1.ORDERS TO C##ROLE_USER_GUEST1;

GRANT SELECT, INSERT, UPDATE, DELETE ON C##M1.ORDERS_DETAILS TO C##ROLE_USER_GUEST1;

CREATE USER C##GUEST1 IDENTIFIED BY GUEST;

GRANT CONNECT TO C##GUEST1;

GRANT C##ROLE_USER_GUEST1 TO C##GUEST1;