connect system/123456;

DROP USER C##M2 CASCADE;

DROP ROLE C##ROLE_USER_GUEST2;

DROP USER C##GUEST2 CASCADE;

CREATE USER C##M2 IDENTIFIED BY a123;

GRANT CONNECT, RESOURCE, CREATE DATABASE LINK, CREATE ROLE, UNLIMITED TABLESPACE TO C##M2;

connect c##m2/a123;

--- enter script in file MX.sql

connect system/meo123;

CREATE ROLE C##ROLE_USER_GUEST2 NOT IDENTIFIED;

GRANT SELECT, INSERT, UPDATE, DELETE ON C##M2.STOCK TO C##ROLE_USER_GUEST2;

GRANT SELECT, INSERT, UPDATE, DELETE ON C##M2.PEN TO C##ROLE_USER_GUEST2;

GRANT SELECT, INSERT, UPDATE, DELETE ON C##M2.STOCK_DETAIL TO C##ROLE_USER_GUEST2;

GRANT SELECT, INSERT, UPDATE, DELETE ON C##M2.IMPORT_PEN TO C##ROLE_USER_GUEST2;

GRANT SELECT, INSERT, UPDATE, DELETE ON C##M2.IMPORT_PEN_DETAIL TO C##ROLE_USER_GUEST2;

GRANT SELECT, INSERT, UPDATE, DELETE ON C##M2.CUSTOMER TO C##ROLE_USER_GUEST2;

GRANT SELECT, INSERT, UPDATE, DELETE ON C##M2.ORDERS TO C##ROLE_USER_GUEST2;

GRANT SELECT, INSERT, UPDATE, DELETE ON C##M2.ORDERS_DETAILS TO C##ROLE_USER_GUEST2;

CREATE USER C##GUEST2 IDENTIFIED BY GUEST;

GRANT CONNECT TO C##GUEST2;

GRANT C##ROLE_USER_GUEST2 TO C##GUEST2;