connect system/meo123;

DROP USER C##ADMIN CASCADE;

DROP ROLE C##ROLE_USER_GUEST3;

DROP USER C##GUEST3 CASCADE;

CREATE USER C##ADMIN IDENTIFIED BY a123;

GRANT CONNECT, RESOURCE, CREATE DATABASE LINK, CREATE ROLE, UNLIMITED TABLESPACE TO C##ADMIN;

connect c##admin/a123;

--- enter script in file admin.sql

connect system/meo123;

CREATE ROLE C##ROLE_USER_GUEST3 NOT IDENTIFIED;

GRANT INSERT, SELECT, UPDATE, DELETE ON C##ADMIN.STOCK TO C##ROLE_USER_GUEST3;

GRANT INSERT, SELECT, UPDATE, DELETE ON C##ADMIN.PEN TO C##ROLE_USER_GUEST3;

GRANT INSERT, SELECT, UPDATE, DELETE ON C##ADMIN.CUSTOMER TO C##ROLE_USER_GUEST3;

---------------------------------------------

CREATE USER C##GUEST3 IDENTIFIED BY GUEST;

GRANT CONNECT TO C##GUEST3;

GRANT C##ROLE_USER_GUEST3 TO C##GUEST3;