--cập nhật tổng đơn hàng sau khi xóa sản phẩm ra khỏi chi tiết đơn hàng
CREATE OR REPLACE TRIGGER ORDERS_DETAILS_AFTER_DELETE AFTER
    DELETE ON ORDERS_DETAILS FOR EACH ROW
DECLARE
    CURR_STOCK_ID NUMBER;
BEGIN
    SELECT
        STOCK_ID INTO CURR_STOCK_ID
    FROM
        ORDERS
    WHERE
        ORDER_ID=:OLD.ORDER_ID;
 -- cập nhật tổng tiền của đơn hàng
    UPDATE ORDERS
    SET
        TOTAL = TOTAL - :OLD.QUATITY * :OLD.PRICE
    WHERE
        ORDERS.ORDER_ID = :OLD.ORDER_ID;
 --cập nhật số lượng pen có trong kho
    UPDATE STOCK_DETAIL
    SET
        STOCK_DETAIL.STOCK_AVAILABLE = STOCK_DETAIL.STOCK_AVAILABLE + :OLD.QUATITY
    WHERE
        STOCK_DETAIL.PEN_ID = :OLD.PEN_ID
        AND STOCK_DETAIL.STOCK_ID=CURR_STOCK_ID;
 --cập nhật số lượng hàng có bên trong kho
    UPDATE C##ADMIN.STOCK@DB_ADMIN
    SET
        STOCK_AVAILABLE = STOCK_AVAILABLE + :OLD.QUATITY
    WHERE
        STOCK_ID=CURR_STOCK_ID;
END;
 --xóa tất cả các chi tiết order trước khi xóa order
CREATE OR REPLACE TRIGGER ORDERS_BEFORE_DELETE BEFORE
DELETE ON ORDERS_DETAILS FOR EACH ROW DECLARE CURR_STOCK_ID NUMBER;
BEGIN
    DELETE FROM ORDERS_DETAILS
    WHERE
        ORDER_ID=:OLD.ORDER_ID;
END;
 --cập nhật số lượng pen có trong kho sau khi xóa khỏi chi tiết import pen
CREATE OR REPLACE TRIGGER IMPORT_PEN_DETAIL_AFTER_DELETE AFTER
DELETE ON IMPORT_PEN_DETAIL FOR EACH ROW DECLARE PEN_EXIST_STOCK INT;
CURR_STOCK_ID INT;
CURR_STOCK_AVAILABLE INT;
CURR_STOCK_CAPACITY INT;
BEGIN
    SELECT
        STOCK_ID INTO CURR_STOCK_ID
    FROM
        IMPORT_PEN
    WHERE
        IMPORT_PEN_ID=:OLD.IMPORT_PEN_ID;
    UPDATE STOCK_DETAIL
    SET
        STOCK_AVAILABLE=STOCK_AVAILABLE-:OLD.QUATITY
    WHERE
        STOCK_ID=CURR_STOCK_ID
        AND PEN_ID=:OLD.PEN_ID;
    UPDATE C##ADMIN.STOCK@DB_ADMIN
    SET
        STOCK_AVAILABLE=STOCK_AVAILABLE-:OLD.QUATITY
    WHERE
        STOCK_ID=CURR_STOCK_ID;
END;
 --xóa tất cả các chi tiết import sau khi xóa trước khi xóa import pen
CREATE OR REPLACE TRIGGER IMPORT_PEN_BEFORE_DELETE BEFORE
DELETE ON IMPORT_PEN FOR EACH ROW DECLARE CURR_STOCK_ID NUMBER;
BEGIN
    DELETE FROM IMPORT_PEN_DETAIL
    WHERE
        IMPORT_PEN_ID=:OLD.IMPORT_PEN_ID;
END;